Created Status model
ExpressionEngine/ExpressionEngine-User-Guide pull request #196
Opened 2021-06-10 19:53 UTC by blairliikala

Added initial Status model info with properties.

2021-06-10 20:40 UTC, ops-andy commented
@blairliikala thanks for the contribution!

- [ ]  @intoeetive can you review this to ensure that technically everything is good to go.
- [ ]  @blairliikala can you please update the _toc.yml file as well to add this new page to the navigation. You'll add this around Line 671.

2021-06-11 05:19 UTC, intoeetive requested changes

2021-06-11 05:19 UTC, intoeetive commented on docs/development/models/member.md
> +#### `group_id`
I believe `group_id` property needs not be in the docks. Or at least marked as deprecated. It is present for the sake of making legacy code work, but when writing new code, `role_id` should always be used

2021-07-30 13:47 UTC, blairliikala commented
A few general questions here:
1. Should the build-in event methods be included in docs such as beforeSave, beforeValidate...etc?  How about getters and setters and validation?  Looking at the Member example that was there before I started, I would assume events would be simply listed, but get/set would be included?
2. Are the class names documented correctly?
3. Some properties are required when _creating_ a model, so I listed them under "Required" but I wonder if this might confuse people when _getting_ a model.  Thoughts?
4. I'm fairly stuck on understanding the custom field models.
5. In all the examples I include a validate step.  Should this stay in?
6. Should services be referenced?  For example, with Log models, there is a legacy service to add logs that works pretty well and has less code.  In these docs, should that be noted as a recommended way to add logs?
7. In some models when I was testing examples, the Site ID was required, but wasn't always listed as required in the model file.  Should this be noted in docs or filed as bugs?  If there is only one site, should Site ID always be included?

2021-07-30 13:53 UTC, blairliikala commented
To elaborate on custom fields, I think having simple example for `relationships`, `grid` and `fluid` would be helpful.  However I couldn't quite figure this out.

2021-08-27 17:09 UTC, robsonsobral commented
Thank you so much, @blairliikala !

Can you give this a chance of merging, @intoeetive ? Better to have partial docs than outdated ones!

2021-10-08 11:46 UTC, intoeetive requested changes
Blair - you did fantastic job creating all this documentation, with real-world detailed examples! Sorry it took me so long to review. I am suggesting just couple of minor changes, and then we're good to merged and publish these!

2021-10-08 11:46 UTC, intoeetive commented on docs/development/models/role.md
> +#### `role_id` Key, ini
should this say "int", not "ini"?

2021-10-08 11:46 UTC, intoeetive commented on docs/development/models/working-with-models.md
> -#### [Role model](development/models/role.md)
I don't think this needs to be removed from this page. Instead, should we add the links from TOC here - so people would have more ways to get to the page they need to?

2021-10-08 11:46 UTC, intoeetive commented on docs/_toc.yml
> +
Can we add "Model" to each name here for clarity? E.g. "Role Model", "Template Model" etc.

2021-10-08 15:42 UTC, blairliikala commented on docs/development/models/role.md
> +#### `role_id` Key, ini
Yep!

2021-10-08 15:43 UTC, blairliikala commented on docs/development/models/working-with-models.md
> -#### [Role model](development/models/role.md)
Andy had said to remove it.  I could see duplicate links not being needed, but either way is fine to me I suppose.

2021-10-08 15:44 UTC, blairliikala commented on docs/_toc.yml
> +
Done!

2021-10-08 15:46 UTC, blairliikala commented on docs/development/models/working-with-models.md
> -#### [Role model](development/models/role.md)
It took me a little bit to combine the knowledge from the Model Service docs and the Models themselves when I was learning, so maybe putting those two closer together somehow would be helpful.  Maybe that intro page should be repurposed around that?

2021-10-08 16:08 UTC, intoeetive commented on docs/development/models/working-with-models.md
> -#### [Role model](development/models/role.md)
Maybe. If you feel you have ideas what to do here, please go ahead in implement. Otherwise we can just leave as it is for now

2021-10-08 16:12 UTC, blairliikala commented on docs/development/models/working-with-models.md
> -#### [Role model](development/models/role.md)
Probably leave as-is and might come back to it for now.

2021-10-11 04:53 UTC, intoeetive approved these changes

2021-10-11 04:54 UTC, merged